// Code generated by tableconv. DO NOT EDIT.
// Source: item.xlsx
package table

import (
	"path/filepath"
	"strconv"
	"strings"
)

// Item 表数据行
type Item struct {
	Id int32 // 物品ID
	Name string // 物品名称
	Stackable bool // 可堆叠
}

// ItemTable Item 表管理器
type ItemTable struct {
	dataDict map[int32]*Item
	dataList []*Item
}

// NewItemTable 创建空的表管理器
func NewItemTable() *ItemTable {
	return &ItemTable{
		dataDict: make(map[int32]*Item),
	}
}

// GetById 按主键获取数据行
func (t *ItemTable) GetById(id int32) *Item {
	return t.dataDict[id]
}

// DataList 返回全量数据列表
func (t *ItemTable) DataList() []*Item {
	return t.dataList
}

// Count 返回数据行数
func (t *ItemTable) Count() int {
	return len(t.dataList)
}

// ParseFromBin 从二进制流读取全部数据
func (t *ItemTable) ParseFromBin(reader *DataStreamReader, rowCount int) {
	t.dataDict = make(map[int32]*Item, rowCount)
	t.dataList = make([]*Item, 0, rowCount)
	for i := 0; i < rowCount; i++ {
		data := &Item{}
		data.Id = reader.ReadInt32()
		data.Name = reader.ReadString()
		data.Stackable = reader.ReadBool()
		t.dataList = append(t.dataList, data)
		t.dataDict[data.Id] = data
	}
}

// Load 从目录加载全部数据，useBin=true 读 bin 格式，否则读 txt 格式
func (t *ItemTable) Load(dir string, useBin bool) error {
	if useBin {
		data, err := LoadBytes(filepath.Join(dir, "item.bin"))
		if err != nil {
			return err
		}
		stbl, err := NewStblReader(data)
		if err != nil {
			return err
		}
		t.ParseFromBin(stbl.Reader, stbl.RowCount)
	} else {
		content, err := LoadText(filepath.Join(dir, "item.txt"))
		if err != nil {
			return err
		}
		t.ParseFromTxt(content)
	}
	return nil
}

// ParseFromTxt 从文本内容读取全部数据
func (t *ItemTable) ParseFromTxt(content string) {
	lines := strings.Split(content, "\n")
	t.dataDict = make(map[int32]*Item)
	t.dataList = nil
	for i := 3; i < len(lines); i++ {
		line := strings.TrimRight(lines[i], "\r")
		if line == "" {
			continue
		}
		fields := strings.Split(line, "\t")
		data := &Item{}
		v0, _ := strconv.ParseInt(fields[0], 10, 32)
		data.Id = int32(v0)
		data.Name = fields[1]
		data.Stackable = fields[2] == "1" || fields[2] == "true"
		t.dataList = append(t.dataList, data)
		t.dataDict[data.Id] = data
	}
}
