// Code generated by tableconv. DO NOT EDIT.
// Source: skill.xlsx
package table

import (
	"path/filepath"
	"strconv"
	"strings"
)

// Skill 表数据行
type Skill struct {
	Id int32 // 技能ID
	Name string // 技能名称
	Cooldown float32 // 冷却时间
	Desc string // 描述
	ServerFlag int32 // 服务器标记
}

// SkillTable Skill 表管理器
type SkillTable struct {
	dataDict map[int32]*Skill
	dataList []*Skill
}

// NewSkillTable 创建空的表管理器
func NewSkillTable() *SkillTable {
	return &SkillTable{
		dataDict: make(map[int32]*Skill),
	}
}

// GetById 按主键获取数据行
func (t *SkillTable) GetById(id int32) *Skill {
	return t.dataDict[id]
}

// DataList 返回全量数据列表
func (t *SkillTable) DataList() []*Skill {
	return t.dataList
}

// Count 返回数据行数
func (t *SkillTable) Count() int {
	return len(t.dataList)
}

// ParseFromBin 从二进制流读取全部数据
func (t *SkillTable) ParseFromBin(reader *DataStreamReader, rowCount int) {
	t.dataDict = make(map[int32]*Skill, rowCount)
	t.dataList = make([]*Skill, 0, rowCount)
	for i := 0; i < rowCount; i++ {
		data := &Skill{}
		data.Id = reader.ReadInt32()
		data.Name = reader.ReadString()
		data.Cooldown = reader.ReadFloat32()
		data.Desc = reader.ReadString()
		data.ServerFlag = reader.ReadInt32()
		t.dataList = append(t.dataList, data)
		t.dataDict[data.Id] = data
	}
}

// Load 从目录加载全部数据，useBin=true 读 bin 格式，否则读 txt 格式
func (t *SkillTable) Load(dir string, useBin bool) error {
	if useBin {
		data, err := LoadBytes(filepath.Join(dir, "skill.bin"))
		if err != nil {
			return err
		}
		stbl, err := NewStblReader(data)
		if err != nil {
			return err
		}
		t.ParseFromBin(stbl.Reader, stbl.RowCount)
	} else {
		content, err := LoadText(filepath.Join(dir, "skill.txt"))
		if err != nil {
			return err
		}
		t.ParseFromTxt(content)
	}
	return nil
}

// ParseFromTxt 从文本内容读取全部数据
func (t *SkillTable) ParseFromTxt(content string) {
	lines := strings.Split(content, "\n")
	t.dataDict = make(map[int32]*Skill)
	t.dataList = nil
	for i := 3; i < len(lines); i++ {
		line := strings.TrimRight(lines[i], "\r")
		if line == "" {
			continue
		}
		fields := strings.Split(line, "\t")
		data := &Skill{}
		v0, _ := strconv.ParseInt(fields[0], 10, 32)
		data.Id = int32(v0)
		data.Name = fields[1]
		v2, _ := strconv.ParseFloat(fields[2], 32)
		data.Cooldown = float32(v2)
		data.Desc = fields[3]
		v4, _ := strconv.ParseInt(fields[4], 10, 32)
		data.ServerFlag = int32(v4)
		t.dataList = append(t.dataList, data)
		t.dataDict[data.Id] = data
	}
}
